defaults:
  - /forward_process: candi_hybrid


_target_: discrete_diffusion.algorithms.candi.CANDI
name: candi 
backbone: dit_candi
T: -1
causal_attention: False
ignore_bos: False
parameterization: subs
loss_type: elbo
time_conditioning: True
temp: 1.0

noise_schedule:
  name: inverse_cdf
  eps: ${noise.eps}
sampler:
  _target_: discrete_diffusion.sampling.candi_sampler.CANDI_Sampler